### ISSUE TITLE
Testing an exception is not thrown

### ISSUE THREAD

**Issue by xmontero** [sebastianbergmann/phpunit-documentation#171]
Here, http://phpunit.de/manual/current/en/writing-tests-for-phpunit.html it says that you can easily test an exception is thrown. But maybe you want to test that an exception is not thrown.

For example, a funcion accepts a number x and must be even. If it is odd raises an InvalidArgumentException.

You might want a a testInvalidArgumentThrowsException with dataprovider [111, 3, 77] as well as testValidArgumentDoesNotThrowException with data provider of [2, 10, 48]

Despite I can test exception with the /*\* xxx */ comment, I try not thrown via a try/catch.

If there is any way to test "not thrown" I suggest to include in that documentation page. If there is no cleaner way, I also suggest to include it in that documentation.

**Comment by J7mbo** [comment]
@sebastianbergmann Warning suppressions can be perfectly valid, and often useful, when the dev using them knows what they're doing and why. Turning failed `file_get_contents()` calls into custom exceptions for a clean object api, for example.

**Comment by Xerkus** [comment]
I found valid use case for testing that exception is not thrown:
I am testing that object is properly initialized by calling getters with declared return types. If object was not initialized fully, getter will throw type error.

Currently, i settled for
```
$tested->getter(); // something that must be set by constructor
self::assertTrue(true, 'Return type ensures this assertion is never reached on failure');
```

**Comment by Kkloe** [comment]
This would be good as we have a method that talks with a service, if that method receives a error it will throw a error, if not we assume everything is ok as we dont have anything to verify it with(and it is not up to us to verify it even), the method has no reason to return a success or true if it didnt detect any errors.

**Comment by inoas** [comment]
We should be able to test if an exception is thrown as much as if it is not thrown.
Basic logic dictates when A then B does not conclude that when B then A.

**Comment by J7mbo** [comment]
It's not that big a deal to add a method that does this, is it?

**Comment by xmontero** [comment]
Hello guys, old thread.

See my documented and extensive answer here: https://stackoverflow.com/a/45850982/1315009

In fact, it **is** actually documented that a method that does not return anything **in fact** is returning a null. All references and plenty of details in that Stack Overflow answer.

So if `doNothing()` is a function that should not throw any exception **and** should not return anything (either because it does not have any `return` statement, either because it has a `return` without any expression following it), then, the correct way to do unit-test this is:

    $this->assertNull( $sut->doNothing() );

This will:

1. Increase the test count.
2. Set green-bar if the funcion `doNothing()` did not throw any exception.
3. Set red-bar if the function does throw any exception.

So, the conclusion is that technically speaking, we do not need a specific function to test that an exception is not throw, as there is a documented method to do this test, actively testing and invoking an assertion.

See the S.O. answer for more reasoned-details. No need to "repeat" content, and better to "concentrate" it in a single place.

**Comment by mikeschinkel** [comment]
I know that this is an old thread but I just came across it, read all the comments and came to the following pattern using a `success()` method to mirror the `fail()` method:

	$object = new MyObject();
	try {
		$object->method_that_might_throw_exception();
		$this->success();
	} catch ( Exception $exception ) {
		$this->fail( "MyObject->method_that_might_throw_exception() failed." );
	}

I can of course add `success()` to my own child of `TestCase` but am wondering if this is not  worthy of inclusion in PHPUnit core, and if not help me understand why not since this approach makes it very explicit that an exception is being tested.

**Comment by VladaHejda** [comment]
The problem is not that *"the test is expected to **not** throw an exception"*.
The problem is "**the test is expected that nothing happens**", and is only reanosable in strict mode (because of *risky* warning).

Current workaround is to call something like `$this->assertTrue(true);`.

My suggetsion is either method `->succeed()` (or `success`) in contrast to method `->fail();` (as @mikeschinkel suggested too),
or method `->expectNothing()` in contrast to method `->expectException()`.

*I'm inclining more for `expectNothing` - imagine test where you call `succeed`, than you call some assertion which fails. So is the result of test success or fail? If you `expectNothing`, it can even fail if there's some assertion, but I think it's not worth. You just expect nothing **or** succeeded assertions.*

**Comment by VladaHejda** [comment]
Well, it has been already implemented (https://github.com/sebastianbergmann/phpunit/issues/2484) as `doesNotPerformAssertions` method.

**Comment by mikeschinkel** [comment]
@VladaHejda Excellent, thanks!

**Comment by mikeschinkel** [comment]
@VladaHejda I think I spoke to soon.  When I use `doesNotPerformAssertions()` instead of `addToAssertionCount(1)` I get those tests reported as _"Risky."_  The goal would be for all those tests to be reported as _"Passed."_

**Comment by VladaHejda** [comment]
@mikaelkael I spoke too soon too. Later I realized, it only supports an annotation `@doesNotPerformAssertions`.. Shame..
(disclaimer: it's not my PR, I only found it today)

**Comment by mikeschinkel** [comment]
@VladaHejda Gotcha.  BTW, you @replied the wrong person. :-)

**Comment by mikaelkael** [comment]
Yes, I think 😁
