### ISSUE TITLE
Note that strict is deprecated in 4.5

### ISSUE THREAD

**Issue by danez** [sebastianbergmann/phpunit-documentation#282]
Please add a note for that.

**Comment by evert** [comment]
Is there a replacement for the strict setting?

**Comment by whatthejeff** [comment]
@evert It was replaced by more granular options:

~~~
--report-useless-tests    Be strict about tests that do not test anything.
--strict-coverage         Be strict about unintentionally covered code.
--disallow-test-output    Be strict about output during tests.
--enforce-time-limit      Enforce time limit based on test size.
~~~

See: sebastianbergmann/phpunit#914.

**Comment by sebastianbergmann** [comment]
I hope to get to this and other things missing from the ChangeLog today.

**Comment by GrahamCampbell** [comment]
> It was replaced by more granular options:

We should document the keys to go into phpunit.xml files too.

**Comment by qrazi** [comment]
Not sure if this is the right issue to report, and not sure if some cluster/caching issue, but searching through Google pointed me to: [https://phpunit.de/manual/current/en/strict-mode.html], which still mentions possibility of `strict="true"`. 

And going through the source I found an undocumented setting (as far as I could find, for current version 4.5): `beStrictAboutTodoAnnotatedTests`. Using that gave me my risky test back in the result... :)

**Comment by potherca** [comment]
The `strict-mode` page seems to be present in versions 4.5, 4.6 and 4.7:

https://phpunit.de/manual/4.5/en/strict-mode.html
https://phpunit.de/manual/4.6/en/strict-mode.html
https://phpunit.de/manual/4.7/en/strict-mode.html

**Comment by hashar** [comment]
In PHPUnit 4.8 setting `struct=true` internally does:
```
        $result['reportUselessTests']          = $flag;
        $result['strictCoverage']              = $flag;
        $result['disallowTestOutput']          = $flag;
        $result['enforceTimeLimit']            = $flag;
        $result['disallowTodoAnnotatedTests']  = $flag;
        $result['deprecatedStrictModeSetting'] = true;
```

Which correspond in `phpunit.xml` to:
```
<phpunit
    beStrictAboutOutputDuringTests="true"
    beStrictAboutTestSize="true"
    beStrictAboutTestsThatDoNotTestAnything="true"
    checkForUnintentionallyCoveredCode="true"
    disallowTodoAnnotatedTests="true"
/>
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
