### ISSUE TITLE
$maxDepth in assertEquals() function appears to be undocumented.

### ISSUE THREAD

**Issue by augwa** [sebastianbergmann/phpunit-documentation#303]
$maxDepth in the function below appears to be undocumented. 

Furthermore searching the code for maxDepth appears that the variable is just passed around, and then assigned once in `PHPUnit_Framework_Constraint_IsEqual` but is never actually used by anything.

``` php
public static function assertEquals($expected, $actual, $message = '', $delta = 0.0, $maxDepth = 10, $canonicalize = false, $ignoreCase = false)
{
    $constraint = new PHPUnit_Framework_Constraint_IsEqual(
        $expected,
        $delta,
        $maxDepth,
        $canonicalize,
        $ignoreCase
    );

    self::assertThat($actual, $constraint, $message);
}
```

**Comment by kamazee** [comment]
Even though [this answer on StackOverflow](http://stackoverflow.com/a/30158867/1099495) suggests it sets the depth of inspecting array or object (and @sebastianbergmann backs it), it doesn't seem to be correct: I don't see the value getting any further than `PHPUnit_Framework_Constraint_IsEqual` and a simple test case illustrates that it doesn't work as SO answer suggests:
```php
<?php

class Test extends PHPUnit_Framework_TestCase
{
    public function testArrayComparison()
    {
        $a[1][2][3] = 0;
        $b[1][2][3] = 1;
        PHPUnit_Framework_Assert::assertEquals($a, $b, '', 0.0, 1);
    }
}
```

The snipped above, being passed to phpunit, yields the following:

```
PHPUnit 4.8.16 by Sebastian Bergmann and contributors.

F

Time: 125 ms, Memory: 4.50Mb

There was 1 failure:

1) Test::testArrayComparison
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     1 => Array (
         2 => Array (
-            3 => 0
+            3 => 1
         )
     )
 )

/Users/alex/test/phpunit/test.php:9
```

Is there an issue with `$maxDepth` or my understanding of how it works?

**Comment by MatTheCat** [comment]
I just discovered the same thing. @sebastianbergmann could you confirm?

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
