### ISSUE TITLE
Spanish translation unavailable

### ISSUE THREAD

**Issue by nelson6e65** [sebastianbergmann/phpunit-documentation#313]
Hi. :smile_cat: 
I realized that there is not an **_spanish**_ translation for documentation.

Maybe I can help. How can I do it? Folk, copy **_`en`**_ folders to **_`es`**_ and translate `*.xml` files? Or there is a **Transifex** project for translations?

**Comment by slayerfat** [comment]
im interested in helping with this as well

**Comment by nelson6e65** [comment]
@slayerfat Maybe you want to join to me? I'm preparing translation for v4.7: 

https://github.com/nelson6e65/phpunit-documentation/tree/es_4.7/src/4.7/es

 :smiley:

**Comment by nelson6e65** [comment]
I was trying to use Transifex Platform to make easier the translation, but apparently is not compatible with this *.XML format. :disappointed_relieved:

**Comment by slayerfat** [comment]
@nelson6e65 alright, will check it out later, does the documentation have contributing rules?

**Comment by nelson6e65** [comment]
Apparently not... I don't know. 

Anyway, I'm following standard for XML:
- Indent: 2 spaces.
- Max. line length 80 (when is possible)

And for translation commits message, just using this template:

```
add|fix: <version>: :es: <file>.xml <small description>.

<optional detailed description>
```

Like: https://github.com/nelson6e65/phpunit-documentation/commit/293f2c317e752f4be6a0e38c870348f459829e97

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
