### ISSUE TITLE
Update documentation for @ticket and @testdox annotations

### ISSUE THREAD

**Issue by duncancumming** [sebastianbergmann/phpunit-documentation#314]
https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.testdox
https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.ticket

These annotations don't have any documentation for what they do, how to use them etc.

**Comment by meitar** [comment]
I was just trying to discover what these annotations, do, too. [This](https://github.com/etsy/phpunit-extensions/wiki/Ticket-Listener/3fdb00b702173d37ededc7f40231d8acb8c89898) page about a "Ticket Listener" is the closest I've come to finding an answer.

**Comment by duncancumming** [comment]
Just discovered some more info about the @testdox one: 
https://docs.joomla.org/Unit_Testing_Best_Practices

If you add the `--testdox` command line parameter, PHPUnit automatically generates some documentations for your running tests.  You can then override those with the @testdox parameter.

**Comment by sebastianbergmann** [comment]
`@ticket` is only an alias for `@group` nowadays. Ticket Listeners were an idea a couple of years ago that turned out to be a bad one.

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
