### ISSUE TITLE
Explain how to use XML configuration

### ISSUE THREAD

**Issue by MCMic** [sebastianbergmann/phpunit-documentation#361]
The page https://phpunit.de/manual/5.3/en/appendixes.configuration.html should explain that the XML configuration should be put in a `phpunit.xml` file or specified with -c option.
It should also state that a root `<phpunit>` node is needed and other nodes are subnodes, this is never stated in the page so at first I directly put a `<listeners>` node in my XML and it did not work.

**Comment by pgrandje** [comment]
Ditto on this!  Seems like there's lots of useful features but the documentation is so thin I can't even see how to use the <groups> tag.  For example, should it be inside or outside the <testsuite> tag?  There's no context provided with the given example.  This is not to mention how, or why, I would use a listener (which seems very useful but I cannot tell!)

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
