### ISSUE TITLE
Question: how do store the DB in memory if the schema is not created by phpunit?

### ISSUE THREAD

**Issue by str** [sebastianbergmann/phpunit-documentation#387]
In the documentation at https://phpunit.de/manual/current/en/database.html#database.what-about-the-database-schema-ddl the first block of code explaining how to connect to the databse, it defines an SQLite in memory. If the DB is in memory, it's created in runtime, right? If phpunit does NOT create the DB schema, how usefull is it to create the DB in memory?

I don't understand the example or the documentation. I undertood the goal of the documentation was to allow a user to be able to learn to create a DBUnit test from scratch until  a dot in the console showing the test ran successfully. IMHO, the DB in RAM only confuses the reader.

**Comment by str** [comment]
The documentation also says:

> This means you as developer have to make sure that the database is correctly setup before running the suite.[...] 
> 1) If you are using a persistent database (not Sqlite Memory) you can easily setup the database once with tools such as phpMyAdmin for MySQL and re-use the database for every test-run

But it does not describe what yo do "if you are NOT using a persistence databse, but SQLite in memory".  Later it also says:

> 2) If you are using libraries such as Doctrine 2 or Propel you can use their APIs to create the database schema you need once before you run the tests

But it doesn't describe what to do if you are not using option 1) nor 2). It also says:  

> You can utilize PHPUnit's Bootstrap and Configuration capabilities to execute this code whenever your tests are run.

But after reading the bootstrap and configuration capabilities, it was not clear how to do that.  For example, in my case I clone the PostgreSQL DB schema from development to test running `createdb -T development testing`. The documentation could be improved adding examples how to do that with the bootstrap and configuration.

It seems the documentation could be improved.

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
