### ISSUE TITLE
error in generateClassFromWsdl inside Generator.php (versions: 4.6, 4.8, 5.5)

### ISSUE THREAD

**Issue by KrzysztofJ** [sebastianbergmann/phpunit-documentation#389]
Hi Sebastian, 

While testing our webservice we discovered that detection of the methods present in wsdl does not work properly in all cases. At present, parsing method name and its arguments happens from the beginning of the line, however there are scenarios where this should happen from the very end of the line.

Please consider following scenario, where $client->__getFunctions() returns following definition of the method and return types:
list(int $return, string $O_STATUS, string $O_ERROR_LIST) NONMEMBER_JOINING(string $I_SM_SRV, string $I_DATA)

as you can see type has a complex definition and current parsing mechanism will not work. When we compare to commonly found examples
int UPSERT_OL_TRANSFER_INV(string $I_SM_SRV, string $I_DATA)
phpunit works as it designed. 

I would like to propose correction to the loop inside generateClassFromWsdl method to cater for the issue, (phpunit-mock-objects\src\Framework\MockObject\Generator.php, affected versions: phpunit 4.6, 4.8, 5.5, possibly others)

current code: 

`

```
        foreach ($_methods as $method) {

        $nameStart = strpos($method, ' ') + 1;
        $nameEnd   = strpos($method, '(');
        $name      = substr($method, $nameStart, $nameEnd - $nameStart);

        if (empty($methods) || in_array($name, $methods)) {
            $args    = explode(
                ',',
                substr(
                    $method,
                    $nameEnd + 1,
                    strpos($method, ')') - $nameEnd - 1
                )
            );
            $numArgs = count($args);

            for ($i = 0; $i < $numArgs; $i++) {
                $args[$i] = substr($args[$i], strpos($args[$i], '$'));
            }

            $methodTemplate->setVar(
                array(
                    'method_name' => $name,
                    'arguments'   => implode(', ', $args)
                )
            );

            $methodsBuffer .= $methodTemplate->render();
        }
    }
```

`

corrected code:

`        

```
        foreach ($_methods as $method) {

        $methodEnd = strrpos($method, ')');
        $nameEnd = strrpos($method, '(');
        $lastSpace = strrpos(substr($method, 0, $nameEnd), ' ');
        $name = substr($method, $lastSpace + 1, ($nameEnd - $lastSpace - 1));

        if (empty($methods) || in_array($name, $methods)) {
            $args    = explode(
                ',', substr($method, $nameEnd + 1, $methodEnd - $nameEnd -1)
            );
            $numArgs = count($args);

            for ($i = 0; $i < $numArgs; $i++) {
                $args[$i] = substr($args[$i], strpos($args[$i], '$'));
            }

            $methodTemplate->setVar(
                array(
                    'method_name' => $name,
                    'arguments'   => implode(', ', $args)
                )
            );

            $methodsBuffer .= $methodTemplate->render();
        }
    }
```

`

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
