### ISSUE TITLE
Consider revising "...PHAR that has all required ... dependencies"

### ISSUE THREAD

**Issue by mjmunger** [sebastianbergmann/phpunit-documentation#425]
On the page: 
https://phpunit.de/manual/current/en/installation.html

This line is a little misleading since DBUnit is no longer in the phar.  Consider revising.

_The easiest way to obtain PHPUnit is to download a PHP Archive (PHAR) that has all required (as well as some optional) dependencies of PHPUnit bundled in a single file._

Perhaps:
The easiest way to obtain PHPUnit is to download a PHP Archive (PHAR) that has all required (as well as some optional) dependencies of PHPUnit bundled in a single file. Note: DBUnit is no longer included in the PHPUnit PHAR archive, and should be [configured as an extension]( https://github.com/sebastianbergmann/dbunit#php-archive-phar).

Reasoning:
After upgrading to the newest versions, I spent an hour scouring the docs trying to figure out why my Traits were not working. I grepped the src from git repo, and discovered that it was not there. So, that wasn't helpful. Thinking, "I must have screwed up the upgrade / install" I returned to the installation section of the docs. Phars are wonderful and uncomplicated, so I wasn't sure how I messed it up, but I was now grasping at straws, and read them over and over looking for what I may have done improperly. It wasn't until Sebastian answered my question on SO that the simple answer was obvious.

**Comment by sebastianbergmann** [comment]
You update to a major version and do not read the changelog?

**Comment by mjmunger** [comment]
Usually, no. But, I got distracted with upgrading to PHP 7.1.2, and seemed to have skipped that. I caused myself a headache, admittedly. Certainly can't blame you for that! :-) Just submitted this as a suggestion to help clarify from an end users perspective. Feel free to close if the addition is not appropriate for the docs. I defer to your expertise.

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
