### ISSUE TITLE
Warn that using TestCaseTrait will bypass DbUnit setUp()

### ISSUE THREAD

**Issue by Kallys** [sebastianbergmann/phpunit-documentation#439]
As a beginner, it took me a while to realize that calling parent::setUp() method will bypass DbUnit\TestCase::setUp() when using TestCaseTrait.
Perhaps it could help other beginners to be warn about that in doc (or maybe that's obvious and I'm just a noob).
```
<?php
use PHPUnit\Framework\TestCase;
use PHPUnit\DbUnit\TestCaseTrait;

class MyTestCase extends TestCase
{
    use TestCaseTrait;

    // Override PHPUnit\DbUnit\TestCase::setUp()
    public function setUp()
    {
        // Will call PHPUnit\Framework\TestCase::setUp() and bypass PHPUnit\DbUnit\TestCase::setUp()
        parent::setUp();
    }
}
?>
```

Thanks!

**Comment by 1fifoto** [comment]
Alternatively, it took me a while to figure out how to invoke DBUnit's setUp when using TestCaseTrait. I also agree that it would help beginners to include something about this in the documentation. 

<?php
class MyTestCase extends PHPUnit_Framework_TestCase {
    // Rename PHPUnit_Extensions_Database_TestCase_Trait::setUp() to traitSetUp
    use PHPUnit_Extensions_Database_TestCase_Trait { setUp as protected traitSetUp; }

    // Overrides PHPUnit_Framework_TestCase::setUp()
    public function setUp()
    {
        // Invokes PHPUnit_Extensions_Database_TestCase_Trait::traitSetUp() (nee setUp),
        // which in turn calls PHPUnit_Framework_TestCase::setUp()
        $this->traitSetUp();
    }
    ...
}
?>

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
