### ISSUE TITLE
Expectation failed with nested mock objects

### ISSUE THREAD

**Issue by llegaz** [sebastianbergmann/phpunit-documentation#448]
Hello PHPUnit community !

I am debuting with unit testing in PHP and I encounter a strange problem. In the setUp() function I build a mocked factory (modelsFactoryMock) that return a mocked object like this:

```
        $companyMock = $this
            ->getMockBuilder(\Company::class)
            ->disableOriginalConstructor()
            ->setMethods([
                'findAll',
                'findByPk',
                'getDbConnection',
            ])
            ->getMock()
        ;
        $companyMock
            ->expects($this->once())
            ->method('getDbConnection')
            ->will(
                $this->returnCallback(
                    function () {
                        var_dump('ok OK ok');   // debug
                        return;
                    }
                )
            )
        ;
```

in the my testing case class I have a test method:
```
public function testCreateCustomer()
{
    $sut = new SUT($this->modelsFactoryMock, $this->formFactoryMock);
    var_dump('first');  // debug
    $customer = $sut->createCustomer($this->arrayData, 1);

    return $customer;
}
```

And finally, in my terminal I get this output:
<pre>
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

......F<b>string(5) "first"
string(8) "ok OK ok"</b>
SS.                                                        10 / 10 (100%)

Time: 452 ms, Memory: 10.00MB

There was 1 failure:

1) Tests\Unit\Managers\Company\CustomerManagerTest::testCreateCustomer
<b>Expectation failed for method name is equal to <string:getDbConnection> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.</b>

FAILURES!
Tests: 10, Assertions: 41, Failures: 1, Skipped: 2.
</pre>

So, with the output I can see that my var_dump calls are rendered nicely and the mock's callback is called once for good but still I keep getting this failure.
I am totally disappointed and I have tried many different solutions to get rid of this problem but I can not get this expectation working properly. Please help me...

Best regards,
Laurent

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
