### ISSUE TITLE
Should indicate pitfalls of bootstrap file, including variable scope and serializtion

### ISSUE THREAD

**Issue by kael-shipman** [sebastianbergmann/phpunit-documentation#459]
I've run into problems with variables defined in the bootstrap file a number of times, so I figured I'd put in a suggestion about it.

It's fair to say I may be using the bootstrap file incorrectly, but I've been largely unable to find useful documentation about how it's supposed to be used. I use it to create or require any test classes that I might need (e.g., concrete test implementations of abstract classes), as well as to define certain global variables for convenience. I also use it to include my main app configuration, which comes in the form of a global variable.

The specific problem I had this time was that I was using a closure to encapsulate a database connection in my main app config, and PHPUnit was complaining about how Closures can't be serialized. That issue specifically is probably related to the fact that I'm using a *really old version* of PHPUnit because I'm testing something for a *really old version* of PHP, but the point stands: I had to dig deep into the source code to figure out where and why my supposedly-global variables were being serialized.

It would be helpful if there were at least a little mention of the dynamics of the bootstrap file in the docs. Maybe something like,

> **Note:** The bootstrap file is not included in the global scope, so variables, functions and classes in it may be subject to certain limitations. In particular, variables declared in the bootstrap file are serialized in order to make them available to test cases, and certain variables don't respond well to this.

Also important to note that I don't actually know that what I've written there is true. That's just something along the lines of which I'd like to see in the docs somewhere.

Thanks again for the great software!

**Comment by sebastianbergmann** [comment]
Dear contributor,

thanks to the hard work by @belanur, @starikovm, @trueromio, and others, the changes outlined in https://github.com/sebastianbergmann/phpunit-documentation/issues/471#issuecomment-336631080 have been implemented.

This repository, https://github.com/sebastianbergmann/phpunit-documentation, is now archived and read-only. The documentation for PHPUnit version prior to PHPUnit 7.0 will no longer be changed or updated. It is still hosted at

* Multiple HTML files: `https://phpunit.de/manual/6.5/en/index.html`
* Multiple HTML files (in a .tar.bz2 archive): `https://phpunit.de/manual/current/en/download.tar.bz2`
* Single HTML file: `https://phpunit.de/manual/current/en/phpunit-book.html`
* PDF: `https://phpunit.de/manual/current/en/phpunit-book.pdf`
* ePub: `https://phpunit.de/manual/current/en/phpunit-book.epub`

Simply replace `6.5` with the version number you are looking for. Simply replace `en` with `fr`, `pt_br`, `ja`, or `zh_cn` to access the French, Brazilian Portuguese, Japanese, or Simplified Chinese translation, respectively.

Starting with the documentation for PHPUnit 7.0, the PHPUnit documentation is hosted at `https://phpunit.readthedocs.io/`.

* The English documentation for PHPUnit is now maintained in the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project
* The French documentation for PHPUnit is now maintained in the [phpunit-documentation-french](https://github.com/sebastianbergmann/phpunit-documentation-french) project
* The Brazilian Portuguese documentation for PHPUnit is now maintained in the [phpunit-documentation-brazilian-portuguese](https://github.com/sebastianbergmann/phpunit-documentation-brazilian-portuguese) project
* The Japanese documentation for PHPUnit is now maintained in the [phpunit-documentation-japanese](https://github.com/sebastianbergmann/phpunit-documentation-japanese) project
* The Simplified Chinese documentation for PHPUnit is now maintained in the [phpunit-documentation-chinese](https://github.com/sebastianbergmann/phpunit-documentation-chinese) project

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another. Please open a new ticket for this issue in one of the new issue trackers (see above).
