### ISSUE TITLE
Obscure reaction on DataProvider exception

### ISSUE THREAD

**Issue by VijitCoder** [sebastianbergmann/phpunit-documentation#480]
If in DataProvider function will be thrown an exception, then tests finishes with this:

```
No tests executed!
Process finished with exit code 0
```

This says absolutely nothing. Is it possible making more eloquent reaction on exception?

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit](https://github.com/sebastianbergmann/phpunit) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by VijitCoder** [comment]
Sorry, I missed that :) I'll remake my request, if it needed.
