### ISSUE TITLE
Documentation omits support for mocking static methods

### ISSUE THREAD

**Issue by edorian** [sebastianbergmann/phpunit-documentation#77]
From sebastianbergmann/phpunit#741:

Following the documentation at http://www.phpunit.de/manual/3.7/en/test-doubles.html, it states that PHPUnit will ignore mocking static methods, as well as private methods. It seems that this is no longer the case (as of 3.5), and Sebastian has written examples of how to mock statics and privates that would be perfect for the documentation: http://sebastian-bergmann.de/archives/883-Stubbing-and-Mocking-Static-Methods.html

**Comment by Paxa** [comment]
After it removed, is there any way to stub static methods now?

**Comment by sebastianbergmann** [comment]
No.

**Comment by timbrownsf** [comment]
It feels gross, but it's something. You can use an inheritance approach, e.g.:
In Experiment.php
```
class Experiment
{
	public static function getVariant($userId, $experimentName) 
	{
		$experiment = self::loadExperimentJson($experimentName):
		return $userId % 10 > 5;  // some sort of bucketing
	} 

	protected static function loadExperimentJson($experimentName)
	{
		// ... do something
	}
}
```

In my ExperimentTest.php
```
class ExperimentTest extends \Experiment
{
	public static function loadExperimentJson($experimentName) 
	{
		return "{
			"name": "TestExperiment",
			"variants": ["a", "b"],
			... etc
		}"
	}
}
```

And then I would use it like so:

```
public function test_Experiment_getVariantForExperiment()
{
	$variant = ExperimentTest::getVariant(123, 'blah');
	$this->assertEquals($variant, 'a');

	$variant = ExperimentTest::getVariant(124, 'blah');
	$this->assertEquals($variant, 'b');
}
```

**Comment by SvenRtbg** [comment]
@timbrownsf No, you can't, if you are calling the static method with `self::` - this will always reference the class itself, not respecting any inherited class. You'd have to use `static::` instead - and that is what this useless discussion is all about. Sebastian had a feature allowing to mock static functions that are being called using `static::`, but the world thought it would allow mocking calls made with `self::`, which it did not. While it was a nice idea trying to help test untestable code, he said he has seen very few useful usage, and much wrong usage - that's why the feature went out again.

**Comment by jannikkeller** [comment]
So there is absolutely NO way to test static methods with the most recent version of PHPUnit?

**Comment by SvenRtbg** [comment]
You can test them. You cannot mock them. That's why using static calls is bad for testability. 

Am 29. Mai 2016 20:33:36 MESZ, schrieb jannikkeller <notifications@github.com>:

**Comment by sebastianbergmann** [comment]
This is not a support forum, sorry.
